name: yatdl
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:yatdl
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_HOST_LISTEN_PORT}:${POSTGRES_LISTEN_PORT}'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - yatdl

  pgadmin4:
    hostname: pgadmin4
    container_name: pgadmin4
    build:
      context: .
      dockerfile: pgadmin4.Dockerfile
    image: pgadmin4:yatdl
    restart: always
    environment:
      - PGADMIN_HOST_LISTEN_PORT=${PGADMIN_HOST_LISTEN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '${PGADMIN_HOST_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}'
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      - yatdl
    depends_on:
      - postgres

  backend:
    hostname: backend
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: backend:yatdl
    restart: always
    tty: true
    # command: 'tail -f /dev/null' # for debugging
    command:
      - bash
      - -c
      - |
        yarn migrate:postgres
        yarn start:dev
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./backend:/home/node/yatdl/backend
    networks:
      - yatdl
    depends_on:
      - postgres
      - pgadmin4

  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend:yatdl
    restart: always
    tty: true
    # backup command: 'tail -f /dev/null' # for debugging
    command: 'yarn start'
    environment:
      - REACT_APP_CLIENT_PORT=${CLIENT_PORT}
      - REACT_APP_SERVER_PORT=${SERVER_PORT}
      - REACT_APP_SERVER_URL=${SERVER_ADDRESS}:${SERVER_PORT}
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    volumes:
      - ./frontend:/home/node/yatdl/frontend
    networks:
      - yatdl
    depends_on:
      - backend
volumes:
  pgadmin4:
    name: "pgadmin4"
  postgres:
    name: "postgres"

networks:
  yatdl:
    name: "yatdl"
