name: yatdl
services:
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - yatdl

  pgadmin4:
    hostname: pgadmin4
    container_name: pgadmin4
    build:
      context: .
      dockerfile: pgadmin4.Dockerfile
    image: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=80
    ports:
      - '5050:80'
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      - yatdl

  node:
    hostname: node
    container_name: node
    build:
      context: .
      dockerfile: node.Dockerfile
    image: node
    restart: always
    tty: true
    command: 'tail -f /dev/null'
    ports:
      - '3000:3000'
    volumes:
      - ./backend-nest:/home/node/yatdl/backend-nest
    networks:
      - yatdl
volumes:
  pgadmin4:
    name: "pgadmin4"
  postgres:
    name: "postgres"

networks:
  yatdl:
    name: "yatdl"
