services:
  postgres-dev:
    container_name: pgdev
    image: postgres:dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data



